### PR TITLE
Play and repeat

### PR DESCRIPTION
**Pull request by dvillaume**
Add a repetitor to the play functions.

### CODE REVIEW

**Review by rfuchs — COMMENTED** [review]
Overall looks good to me, with a few comments, see below. My primary concern is with the usage of `avformat_seek_file` and then there's a few minor style issues.

Lastly, since this is a single feature/change, all these commits should be squashed into a single one, together with a more descriptive commit messages describing the change.

Since these are all minor issues, I can handle them if you prefer. Let me know.

**Comment by dvillaume** [comment]
@rfuchs i will accept your poposal to handle this, if that doesn't bother you too much.

**Comment by rfuchs** [comment]
So ac2a6f07cb would be my cleaned up version of this. See if it works for you. (Flag has been renamed to `repeat-times` from `repeat_times` for consistency)

**Comment by amessina** [comment]
While not related directly to repeat, it would be useful to play a list of files in succession, i.e. play-media `file=file1&file2&...1` `db-id=id1&id2&...`.

**Comment by rfuchs** [comment]
@amessina pull requests welcome :smile:

**Comment by amessina** [comment]
> @amessina pull requests welcome

Most certainly -- I just don't know C :(

**Pull request closed without merging**
