### PR TITLE
Improve used SSL ciphers

### PR DESCRIPTION
**Pull request by timgws**
Remove a number of SSLv3 ciphers, increase the key size generated by `RSA_generate_key_ex` (fixes some issues with Chrome WebRTC)

The following items (highlighted in red) shows the ciphers that are disabled with this change.

```diff
--- included-current.txt	2020-01-30 14:34:39.000000000 +1100
+++ included-new.txt	2020-01-30 14:34:45.000000000 +1100
@@ -14,7 +14,6 @@
 DHE-RSA-CAMELLIA256-SHA256 TLSv1.2 Kx=DH       Au=RSA  Enc=Camellia(256) Mac=SHA256
 DHE-RSA-CAMELLIA256-SHA SSLv3 Kx=DH       Au=RSA  Enc=Camellia(256) Mac=SHA1
 GOST2001-GOST89-GOST89  SSLv3 Kx=GOST     Au=GOST01 Enc=GOST-28178-89-CNT Mac=GOST89IMIT
-AECDH-AES256-SHA        SSLv3 Kx=ECDH     Au=None Enc=AES(256)  Mac=SHA1
 AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
 AES256-SHA256           TLSv1.2 Kx=RSA      Au=RSA  Enc=AES(256)  Mac=SHA256
 AES256-SHA              SSLv3 Kx=RSA      Au=RSA  Enc=AES(256)  Mac=SHA1
@@ -31,14 +30,8 @@
 DHE-RSA-AES128-SHA      SSLv3 Kx=DH       Au=RSA  Enc=AES(128)  Mac=SHA1
 DHE-RSA-CAMELLIA128-SHA256 TLSv1.2 Kx=DH       Au=RSA  Enc=Camellia(128) Mac=SHA256
 DHE-RSA-CAMELLIA128-SHA SSLv3 Kx=DH       Au=RSA  Enc=Camellia(128) Mac=SHA1
-AECDH-AES128-SHA        SSLv3 Kx=ECDH     Au=None Enc=AES(128)  Mac=SHA1
 AES128-GCM-SHA256       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(128) Mac=AEAD
 AES128-SHA256           TLSv1.2 Kx=RSA      Au=RSA  Enc=AES(128)  Mac=SHA256
 AES128-SHA              SSLv3 Kx=RSA      Au=RSA  Enc=AES(128)  Mac=SHA1
 CAMELLIA128-SHA256      TLSv1.2 Kx=RSA      Au=RSA  Enc=Camellia(128) Mac=SHA256
 CAMELLIA128-SHA         SSLv3 Kx=RSA      Au=RSA  Enc=Camellia(128) Mac=SHA1
-ECDHE-RSA-DES-CBC3-SHA  SSLv3 Kx=ECDH     Au=RSA  Enc=3DES(168) Mac=SHA1
-ECDHE-ECDSA-DES-CBC3-SHA SSLv3 Kx=ECDH     Au=ECDSA Enc=3DES(168) Mac=SHA1
-EDH-RSA-DES-CBC3-SHA    SSLv3 Kx=DH       Au=RSA  Enc=3DES(168) Mac=SHA1
-AECDH-DES-CBC3-SHA      SSLv3 Kx=ECDH     Au=None Enc=3DES(168) Mac=SHA1
-DES-CBC3-SHA            SSLv3 Kx=RSA      Au=RSA  Enc=3DES(168) Mac=SHA1
```

### CODE REVIEW

**Comment by timgws** [comment]
Reasons for removing these ciphers can be found at https://ciphersuite.info/

For example, with AECDH-AES128-SHA (TLS_ECDH_anon_WITH_AES_128_CBC_SHA) it is easily able to be used with to cause a Man in the Middle attack in some environments*

**Comment by rfuchs** [comment]
Do you know if this is in line with other DTLS-SRTP/WebRTC implementations? I don't want to break interoperability. Perhaps this should be made configurable.

**Comment by timgws** [comment]
> Do you know if this is in line with other DTLS-SRTP/WebRTC implementations?

I honestly have no idea, it would be amazing to have both of these parameters be configurable.

**Comment by timgws** [comment]
Thanks so much for this, @rfuchs!

**Pull request closed without merging**
