### PR TITLE
Refactoring $RTP_IP/$RTP_IP6 so we can use a number of parameters for --interface command line

### PR DESCRIPTION
**Pull request by sybasesql**

### CODE REVIEW

**Comment by rfuchs** [comment]
Thanks for this. Do you think it may be better to get rid of $RTP_IP6 altogether, since it does the same thing as $RTP_IP?

**Comment by rfuchs** [comment]
Actually, nevermind my last comment. The init script should still support it for compatibility nevertheless.

**Comment by sybasesql** [comment]
Yep! It'll even better and simpler.

**Comment by sybasesql** [comment]
Well, with this pull request there are changes in the structure of the configuration file (rtpengine.sysconfig), so changes will be anyway and i afraid not backward compatibility.
e.g. deleting $RTP_ADV_IP/$RTP_ADV_IP6 and transforming $RTP_IP/$RTP_IP6 into array.

**Comment by rfuchs** [comment]
Ah yes, you're right. I'll go ahead and remove it then.

**Pull request merged**
