### PR TITLE
Various minor improvements

### PR DESCRIPTION
**Pull request by lbalaceanu**
* Report own/foreign/total sessions to Graphite

* Printing severity level within every log message

>     rtpengine[4613]: ERR: Socket connect failed. fd: 25, Reason: Connection refused
                                                             vs
    rtpengine[4613]: Socket connect failed. fd: 25, Reason: Connection refused

* Print relay IP information: add relay IP info in MDR, `rtpengine-ctl list sessions <Call-ID>`, call_destroy()

* Adding redis_expires parameter: default is 86400, but this can be configured

### CODE REVIEW

**Comment by rfuchs** [comment]
278561ba seems to duplicate the log severity when logging to stderr (`log_to_stderr()` already includes this).

**Comment by lbalaceanu** [comment]
Hi Richard - you are right. To solve this, I would delete the printing of the log severity in the log_to_stderr() which solves the problem. Agree?

**Comment by rfuchs** [comment]
Works for me

**Comment by lbalaceanu** [comment]
Ok, and how about making --log-stderr available from ngcp-rtpengine-daemon.init + adding in ngcp-rtpengine-daemon.default # LOG_STDERR="no"?

**Comment by rfuchs** [comment]
Not sure how useful that is from an init.d script, but hey, why not :)

**Comment by lbalaceanu** [comment]
Updated the pull request.

**Pull request merged**
