### PR TITLE
Specific REDIS read and write databases

### PR DESCRIPTION
**Pull request by smititelu**
Able to specify now, in the config, the redis databases from which rtpengine
should read and write session information.

### CODE REVIEW

**Comment by rfuchs** [comment]
Can you explain the purpose of having two different databases?

**Comment by smititelu** [comment]
This is useful mainly when thinking of redundancy of redis databases.

Suppose a master-slave configuration of redis databases. Rtpengines restore sessions from the slave redis and write new session in the master redis. The master synchronize its content with the slaves. If one slave redis fails, the other slaves still have info about _all_ sessions.

**Comment by rfuchs** [comment]
What I'm missing here is a fallback, or backwards compatibility if you wish, where it's possible to just specify one DB and have it used for both reads and writes.

Also let me take this opportunity to give you a heads up. We'll be integrating our own Redis code into the main rtpengine repo in the near future, thus obsoleting the entire plugin system and hopefully making everybody's life easier.

**Comment by smititelu** [comment]
You are right. I have overlooked the backwards compatibility when implementing. I've updated pull request to use REDIS_READ/WRITE if present in the config; if not, old REDIS is used.

Integrating Redis code into rtpengine would be nice. We are looking forward to it. Thanks for the heads up :).

**Comment by pkuzak** [comment]
Hey Richard, that's really nice to hear that you plan to integrate the Redis code into the _rtpengine_ repo and we are definitely looking forward to it. Can you maybe specify (if possible) the time frame "near future" a little bit more? I am asking because it might have impact on our internal planning and depending on your answer we might consider waiting for you to finish the integration before investing more time in further improving https://github.com/ngvoice/rtpengine-redis-plugin

**Comment by rfuchs** [comment]
Very near future, I may be able to do it this week.

**Comment by smititelu** [comment]
Closing this pull request. Will make another one taking considering the integrated plugin.

**Pull request closed without merging**
