### PR TITLE
Add stats for ipv4/ipv6/mixed media calls

### PR DESCRIPTION
**Pull request by smititelu**
Also Send stats for ipv4/ipv6/mixed media calls to graphite

### CODE REVIEW

**Comment by rfuchs** [comment]
I believe there's a problem if a call has one side switching from v4 to v6 (or vice versa) during a re-invite - the stats would go out of sync then, would they not? In fact it looks like that any time a call sees two or more answers it would be counted multiple times?

**Comment by smititelu** [comment]
Indeed I have overlooked the re-invites. Will update the PR accordingly.

Question: Do you think there is any valid scenario where calling rtpengine_answer() when call is already answered is helpful? Or this should just be guarded out, for these statistics?

Thanks,
Stefan

**Comment by rfuchs** [comment]
> Indeed I have overlooked the re-invites. Will update the PR accordingly.
> 
> Question: Do you think there is any valid scenario where calling rtpengine_answer() when call is already answered is helpful? Or this should just be guarded out, for these statistics?

Yes, this is very commonly done for a number of reasons, and can include changing the endpoint and address family.

**Comment by smititelu** [comment]
I've updated PR to consider separate offer/answer ip 4/6 stats and to update the stats for each new offer/answer.

I've basically tested it and it looks fine. Still, I want to do more complex tests and will post later.

**Comment by smititelu** [comment]
I've found no issues in my tests, so far, with these new statistics. From my point of view PR can be merged.

**Pull request merged**
